{"name": "test_log3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.Test_Log object at 0x000000000376F128>\n\n    def test_log3(self):\n>       assert 0\nE       assert 0\n\nscripts\\test_login.py:7: AssertionError"}, "start": 1583380593252, "stop": 1583380593252, "uuid": "fff0bf94-59b6-498c-a3e9-b5e2a2e102ff", "historyId": "ac2d7660f0fc87964197d5ab4cabe44d", "testCaseId": "5907fef17455ecfc4a6882b0e4daa97c", "fullName": "scripts.test_login.Test_Log#test_log3", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Log"}, {"name": "host", "value": "PC-20200229QXQF"}, {"name": "thread", "value": "4516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}